### ISSUE TITLE
adasteam.ca should not be in an <iframe>

### ISSUE THREAD

**Issue by eddieantonio** [adas-team/adas-team.github.io#32]
The entire page is embedded in an `<iframe>` and it break a lot of things, and makes it look bad on mobile :(

Try to get the DNS configured to point to adas-team.github.io and add an appropriate `CNAME` to the root of the repository.

**Comment by MandyMeindersma** [comment]
I turned off gripping (that's free) and it fixed it... but now we have github.io link displayed instead of adasteam.ca before. see photo. 

![image](https://user-images.githubusercontent.com/17459171/49356852-611cd780-f68a-11e8-8662-23906042f96f.png)

**Comment by eddieantonio** [comment]
> ![image](https://user-images.githubusercontent.com/17459171/49356765-0e432000-f68a-11e8-99c7-6327da5f8873.png)
> We have to pay for the DNS stuff..... :( I guess we could

Who provides the domain? Is it a domain name registrar? Were they giving out the .ca domains for free? (I had assumed you were paying for it to begin with...)

**Comment by MandyMeindersma** [comment]
Sorry yes we already pay for it. We would just have to may more per month. (and hook up and execs credit card that it would charge every month)

**Comment by MandyMeindersma** [comment]
We have the domain paid until 2023 or something?

**Comment by MandyMeindersma** [comment]
We have the domain paid until 2023 or something?

We got it through webnames

**Comment by eddieantonio** [comment]
:/ I mean, what's the budget? It shouldn't be _horribly_ expense per month? I pay less than $20 CAD for eddieantonio.ca through Hover.

**Comment by MandyMeindersma** [comment]
It's not the money that's an issue, it would mean an exec would have to hook up their credit card. This would have to be changed every year and if someone forgets to change it then an old exec would keep getting charged. Maybe the department has a card we could use..... Interesting.....

Currently it's fixed with the gripping thing though. How unprofessional is it to have "adasteam.github.io" instead of "adasteam.ca"

**Comment by eddieantonio** [comment]
Makes sense.

I don't think a .github.io domain is unprofessional, but it probably depends on people's perceptions of what GitHub even _is_! Yeah, the department may have a card you could use... 🙃

**Comment by eddieantonio** [comment]
We will deal with https://adas-team.github.io/ for now, since WebNames is dumbstupid
